# CPACK
# https://cmake.org/cmake/help/book/mastering-cmake/chapter/Packaging%20With%20CPack.html
# https://decovar.dev/blog/2021/09/23/cmake-cpack-package-deb-apt/
set(PackagingTemplatesDir "${CMAKE_CURRENT_SOURCE_DIR}/cmake")

set(CPACK_PACKAGE_NAME "More Orb SLAM(${PROJECT_NAME})")
set(CPACK_PACKAGE_VENDOR "Martinrea Alfield")
set(CPACK_PACKAGE_DESCRIPTION "${PROJECT_DESCRIPTION}")
set(CPACK_DEBIAN_PACKAGE_NAME "${CPACK_PACKAGE_NAME}")
# set(CPACK_RPM_PACKAGE_NAME "${CPACK_PACKAGE_NAME}")
set(CPACK_PACKAGE_HOMEPAGE_URL "${PROJECT_HOMEPAGE_URL}")
set(CPACK_PACKAGE_MAINTAINER "David Petkovsek")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_MAINTAINER}")
# set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
# set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_DEBIAN_PACKAGE_NAME "lib${PROJECT_NAME}-dev")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libstdc++-12-dev, libstdc++-12-pic, libeigen3-dev")
set(CPACK_DEBIAN_PACKAGE_SUGGESTS "clang, clang++, libopencv-dev, cmake, pkg-config, pkg-conf")

# set(CPACK_RPM_PACKAGE_NAME "lib${PROJECT_NAME}-devel")
# set(CPACK_RPM_PACKAGE_SUGGESTS "${CPACK_DEBIAN_PACKAGE_SUGGESTS}")

set(CPACK_DEB_COMPONENT_INSTALL ON)
# set(CPACK_RPM_COMPONENT_INSTALL ON)
set(CPACK_NSIS_COMPONENT_INSTALL ON)
set(CPACK_DEBIAN_COMPRESSION_TYPE "xz")

set(PKG_CONFIG_FILE_NAME "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}.pc")
configure_file("${PackagingTemplatesDir}/pkgconfig.pc.in" "${PKG_CONFIG_FILE_NAME}" @ONLY)
install(FILES "${PKG_CONFIG_FILE_NAME}"
      DESTINATION "${CMAKE_INSTALL_LIBDIR}/pkgconfig"
)
include(CPack)